### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by TGC-TECH** [oxyry/reabble#1]
If you are going to create a GitHub then please upload code to it.

**Comment by 1a57danc3** [comment]
Try miniflux
https://github.com/ky0nch3ng/miniflux-legacy

**Comment by TGC-TECH** [comment]
Looks cool, I just wish it had the same E Ink optimized page scroll
features. Though being actually open source I am sure someone could fork
it.


On Aug 30, 2018 at 3:29 AM, <КЧоиснзиg <notifications@github.com>> wrote:

Try miniflux
https://github.com/ky0nch3ng/miniflux-legacy

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/weijarz/reabble/issues/1#issuecomment-417218452>, or mute
the thread

**Comment by dynamohuang** [comment]
Good job. Wish to  open source !  We do it better together

**Comment by helmut72** [comment]
Would be great to have it open source and support Fever API to connect to self-hosted solutions like TT-RSS, Minflux, FreshRSS...

**Comment by weijarz** [comment]
@helmut72 Fever API support is planned.  It will be added in the next three months.

**Comment by helmut72** [comment]
Thanks for supporting Fever API. 2 Months to go ;)

**Comment by helmut72** [comment]
-1 month to go ;)

**Comment by helmut72** [comment]
Any news regarding Fever API? Outside/sunny season starts in northern part of the world. Looks like going the route with Hisense A5 becomes a better joice using a RSS App. For example FeedMe, which supports Fever, TT-RSS API and many more.

**Comment by raining1123** [comment]
> @helmut72 Fever API support is planned. It will be added in the next three months.

哈哈哈都快3年了~

**Comment by helmut72** [comment]
Using instead Hisense A7CC and I'm completely happy if I'm out in the sun. It's a whole better choice to use a E-Ink phone with Android if you want text-related content, but don't want to be limited to E-Books only. You can install what you need.
