### ISSUE TITLE
个人感觉kindle上旧版体验更好

### ISSUE THREAD

**Issue by halu886** [oxyry/reabble#11]
1. 在kindle中的浏览器上方存在一个行工具栏，但是在页面中的顶部新增了一个工具栏，缩小页面显示内容的区域
2. 阅读文章的区域，旧版页面点击的功能相似kindle阅读书籍的功能，使用起来很顺畅，但是新版把大部分操作放在页面的顶部的功能栏中，对于kindle用户来说稍微有点不友好

**Comment by halu886** [comment]
麻烦也把旧版也开放出来，谢谢~:)

**Comment by billiskilled** [comment]
兄弟，为什么我的这个网站已经崩了？最近都打不开，你能打开吗？感觉有一个多月了吧，网站一直都是崩溃的。麻烦告诉一下你登录的网址是什么呀？多谢多谢！

**Comment by billiskilled** [comment]
卧槽，竟然网站能进去了，我都想要自己写一个了。干。

**Comment by weijarz** [comment]
@billiskilled 国内的话要用 [reabble.cn](https://reabble.cn)  不能用  reabble.com（这个已经被墙了）

**Comment by billiskilled** [comment]
@weijarz  嗯，多谢。现在好了，能用了，我觉得有可能是浏览器没有清理缓存，然后网站升级的时候导致的网站崩溃吧。有一段时间想用的时候，chrome浏览器和kindle浏览器都进不去reabble.cn网站，都显示app启动失败啥的。
