### ISSUE TITLE
下载的格式为什么是英文字体？

### ISSUE THREAD

**Issue by taotao2010** [oxyry/reabble#12]
下载回来的字体是英文模式，不能选圆体

另外，页面的进度条能不能改成具体数字？

PS：旧版好好的为什么要改版？毕竟大家都是付过钱的啊~

**Comment by Martino1972** [comment]
The New "send to kindle" service only sends 25 unread items, Is it a code error? Or is it a user configuration error?

**Comment by oxyry** [comment]
现在可以在推送设置页面设置语言了，设成中文后可以选中文字体。

**Comment by oxyry** [comment]
@Martino1972 
If its sent in <https://reabble.com/settings/push> , the quantity is the quantity you choose (max 100).
If its sent in App/List Menu/Send to Kindle, the number of articles is fixed at 25, but you can send it multiple times.
