### ISSUE TITLE
登录时显示not found

### ISSUE THREAD

**Issue by amourssdk** [oxyry/reabble#14]
bxpwibbxkjrb
电脑浏览器也是这样

**Comment by weijarz** [comment]
我这里复现不了。
是登录页面本身not found呢还是点了登录按钮后显示not found?

**Comment by amourssdk** [comment]
帐号为646424187@qq.com
登录码为&nbsp;bxpwibbxkjrb
输入后是这样



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"weijarz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 下午4:24
收件人:&nbsp;"oxyry/reabble"<reabble@noreply.github.com&gt;;
抄送:&nbsp;"1"<646424187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oxyry/reabble] 登录时显示not found (#14)




我这里复现不了。
 是登录页面本身not found呢还是点了登录按钮后显示not found?

**Comment by weijarz** [comment]
现在不需要登录码了，直接在主页点登录就行
