### ISSUE TITLE
pc本地

### ISSUE THREAD

**Issue by Hello-XPH** [oxyry/reabble#17]
大佬有没有打算弄pc本地的想法.有的话，希望不要上microsoft store。好多好的RSS上了microsoft store，又需要付费就必须登录microsoft。不是没有microsoft帐号，而是不想登录microsoft 。而且翻墙的时候microsoft store也不知道怎么了打开没有反应，这个问题难受死了。使用的人一般都是翻墙用户，国内有几个人知道使用RSS。建议不要上架microsoft store，大佬看看。
![84894806-0021ec80-b0d4-11ea-960e-382b265720f4](https://user-images.githubusercontent.com/56664327/84896207-2052ab00-b0d6-11ea-9f4b-4496fa662011.png)
![Snipaste_2020-06-17_20-06-36](https://user-images.githubusercontent.com/56664327/84896198-1b8df700-b0d6-11ea-94cb-f8b2befb2395.png)
希望大佬的RSS阅读器越做越好。

**Comment by Hello-XPH** [comment]
pc版本付费我支持就是不要上microsoft store.

**Comment by weijarz** [comment]
这里只有网页版，不会有PC版。
