### ISSUE TITLE
当前版本的文章列表滚动体验不好

### ISSUE THREAD

**Issue by iblueer** [oxyry/reabble#22]
文章正文已经实装了按键翻页，但是文章列表还是靠上下滑动，建议也增加按键翻页按钮。目前滑动翻页的时候速度过快，体验也不好。

**Comment by weijarz** [comment]
文章列表下面不是也有翻页按钮吗？

**Comment by iblueer** [comment]
啊，文章列表那个按钮比较隐蔽，没发现😂已经看到了

发自我的iPhone
