### ISSUE TITLE
希望放宽邮箱设置. 手里有一款文石的设备,也想使用这个功能

### ISSUE THREAD

**Issue by androidfans** [oxyry/reabble#23]
或者起码开放下outlook, 我自己用邮件转发功能发送

**Comment by weijarz** [comment]
文石也有类似的发送到指定邮箱会自动同步到设备的功能吗？

**Comment by androidfans** [comment]
> 文石也有类似的发送到指定邮箱会自动同步到设备的功能吗？

没有这个功能. 但是他能登录自己的邮箱, 可以手动下载.
@weijarz

**Comment by weijarz** [comment]
@androidfans 就是说在文石这个设备上有邮箱App,然后可以下载附件到本地？你说的邮件转发是什么意思？

**Comment by androidfans** [comment]
@weijarz  对, 就是这个意思.  邮件转发的意思是如果你担心多个设备会增加reabble的流量压力. 可以只开放一个outlook邮箱. outlook可以设置规则,收到邮件后自动转发到其他多个邮箱. 这样你的server压力就小了

**Comment by weijarz** [comment]
已经支持其它邮箱。
经测试gmail和qq mail可以收到，但outlook不行，即使把发件邮箱添加到安全列表中。

**Comment by androidfans** [comment]
感谢 我试下
