### ISSUE TITLE
怎么把词典功能加到工具条

### ISSUE THREAD

**Issue by Standard0011** [oxyry/reabble#26]
十分需要更快捷的点击 "词典" 功能. 
现在每次想调出词典,都需要点击 "三个点 -> 词典 -> 点击单词".  并不方便.
请问下,我是否可以把 "词典" 也放入 那个 "工具条" 中?

或者 
在 kindle 中,用 reabble 阅读,还有其他更方便的调用 "词典" 的办法吗?

**Comment by Diluo001** [comment]
另外, kindle 中 阅读,是不是只能向下翻页, 无法向上?

**Comment by weijarz** [comment]
只能点击工具栏按钮，无法做到象Kindle原生那样长按。
明天我试试把按钮加到工具栏。
或者你可以把英文文章推送到Kindle,这样就可以利用原生词典了。

**Comment by Standard0011** [comment]
谢谢, 请尽量加到工具栏吧.

**Comment by Standard0011** [comment]
感谢作者,你的作品,对我十分有用.  这几天才知道有这么个程序. 十分感谢.

**Comment by Standard0011** [comment]
今天试了下 推送到 Kindle. 经提醒,才知道这个功能.  更完美了. 谢谢.
