### ISSUE TITLE
Kindle 固件升级至 5.13.7 后显示效果变差

### ISSUE THREAD

**Issue by yEs1do** [oxyry/reabble#28]
在 Kindle 阅读器固件升级至 5.13.7 后，Reabble 页面需要下滑一点才能看到所有页面内容，较影响操作，希望适配（比如增加分辨率选项或者开关）

**Comment by weijarz** [comment]
你好，

你可以用 Kindle 打开 http://pub.oxyry.com/kindle/  这个页面，测试下哪个方案没有滚动条。

**Comment by yEs1do** [comment]
已逐一尝试，五种方案全部存在滚动条

**Comment by WeiFengJL** [comment]
同样情况，希望可以优化适配

**Comment by nyavana** [comment]
链接五种方式都尝试了，均存在滚动条。
按照之前#4 里面双击左上角的方法确实可以隐藏滚动条，但是最下部分会有几个像素无法完整显示，见截图。

设备: kindle paperwhite 5 (11 gen)
os版本: 5.14.3

截图：
![screenshot_2022_08_10T07_14_58-0700](https://user-images.githubusercontent.com/33804090/183924467-56a989f3-1b63-44ed-8ff0-4060b5d49ceb.png)

双击前：
![screenshot_2022_08_10T07_22_55-0700](https://user-images.githubusercontent.com/33804090/183926058-82c1b1d3-d543-4b54-97ba-b8f5a1ba8f9c.png)

双击后：
![screenshot_2022_08_10T07_23_01-0700](https://user-images.githubusercontent.com/33804090/183926085-09f1b8f1-f782-4cbe-bb26-b923e8aa0311.png)

**Comment by WeiFengJL** [comment]
虽然隐藏滚动条，但是最下部分会有几个像素无法完整显示。导致看着好不顺眼，网页版现在是没更新了吗，这个问题能不能尽快解决呢

**Comment by nyavana** [comment]
> 虽然隐藏滚动条，但是最下部分会有几个像素无法完整显示。导致看着好不顺眼，网页版现在是没更新了吗，这个问题能不能尽快解决呢

看起来应该是存在很久了，开发者最近好像也没回过GitHub，我明天微信问一下他🤔

**Comment by weijarz** [comment]
@WeiFengJL @ggdxwz 这二天我会入个paperwhite5解决这个问题

**Comment by nyavana** [comment]
> @WeiFengJL @ggdxwz 这二天我会入个paperwhite5解决这个问题

谢谢@weijarz ，如果需要的话我可以用手上的kpw5配合你测试，这样你可能就不用买了

**Comment by WeiFengJL** [comment]
感谢，但似乎不是只有KPW5会，入门版Kindle8也会

**Comment by nyavana** [comment]
> 感谢，但似乎不是只有KPW5会，入门版Kindle8也会

感觉是新版状态栏高度增加了，改一下viewport大小应该就可以解决

**Comment by WeiFengJL** [comment]
嗯嗯，感觉就是浏览器新版改版后导致的

**Comment by weijarz** [comment]
@ggdxwz 程序里是用的检测到的大小，在别的浏览器里都没问题，就是Kindle的BUG。
按楼上说的整体缩小都能出滚动条，我也不能确定一定能解决，等几天后到货了我看看有没有绕过的办法。

**Comment by weijarz** [comment]
看了一下原因应该是Kindle更新固件后，它的浏览器上面的工具栏部分更高了，但浏览器本身显示区的高度还是定死之前的，导致出现滚动条，即使是空白页面也会出现，真是离了个大谱，亚马逊真是对浏览器完全不上心。

这边已经调整已适应这个情况，下面缩进了32像素以便让之前被截断的底边工具栏全部显示。
右边会缩进16像素，让App内的滚动条出现在浏览器的固定滚动条左边，否则会被浏览器的滚动条重叠。
