### ISSUE TITLE
希望日后能支持其他邮箱或支持webdav

### ISSUE THREAD

**Issue by zzq-2002** [oxyry/reabble#32]
Kindle 中国电子书店将于 2023 年 6 月 30 日停止运营，2024-06-30后将不再能使用Send to Kindle。

**Comment by weijarz** [comment]
在8月前会支持推送到第三方邮箱，并且转用epub格式。
Send to Kindle只是国内 @kindle.cn 不能用了而已，绑定到美国亚马逊就可以用 @kindle.com 推送了，国行买的也能绑定。

**Comment by weijarz** [comment]
已经支持其它邮箱。
经测试gmail和qq mail可以收到，但outlook不行，即使把发件邮箱添加到安全列表中。

**Comment by zzq-2002** [comment]
十分感谢。
