### ISSUE TITLE
"Please match the requested format"?

### ISSUE THREAD

**Issue by HoudyDoody** [oxyry/reabble#36]
Installed "Send To Kindle" on Firefox 105.0.1 (64-bit). Added my kindle to "Send to Address" and selected "@free.kindle.com." Copied and pasted (Ctrl-C, Ctrl-V) a 320-page .pdf to "Paste content here" and selected "Send." Got "Please match the requested format." Tried again with same document, but from .docx source with same result. What does "Please match the requested format" mean? How do I fix this?

**Comment by weijarz** [comment]
This site cannot be used to send entire files directly. 
To send a pdf file, please use https://www.amazon.com/sendtokindle/email
