### ISSUE TITLE
Kindle voyage，v5.13.6，无法打开网站

### ISSUE THREAD

**Issue by Margaret-Fawkes** [oxyry/reabble#37]
已经清除Kindle浏览器cookies和历史记录，已经重启Kindle。
直接访问reabble.cn主页，弹出提示“网站无法访问。很抱歉，浏览器无法打开该网站。”
用iOS safari访问正常。

**Comment by weijarz** [comment]
我也是这个设备，可以打开。KV上打开别的网站都正常就reabble不行？

**Comment by Margaret-Fawkes** [comment]
> 

是的，我随便开了度盘首页，都可以的，只有reabble不行，会展示登陆按钮，然后弹出提示。

现在只能试试重置系统了，太费事了，唉，重置中。

**Comment by weijarz** [comment]
有登录界面，只是点了登录后才出现错误？
以前可以登录吗？

**Comment by Margaret-Fawkes** [comment]
> 

感谢大佬回复，我费劲巴拉重置了整个系统，恢复了！！

害得我开电脑一通备份，真是麻烦啊。

复盘一下，是这样的。

我日常一直用pc浏览器阅读的，但一直在Kindle上保持登陆状态。
今天打开Kindle时照常显示未读列表，一秒后突然就弹出“无法访问”弹窗。确认弹窗后白屏。刷新无效，继续弹。
清浏览器cookies，清历史记录，重启系统无效。访问摆渡主页正常。
电量充裕。WiFi正常。同WiFi下iOS safari访问主页正常。

清除Kindle cookies后展示的是带登陆按钮的网站主页，按钮已经显示了，然后秒弹“无法访问”，继续白屏。

我怀疑Kindle浏览器可能崩溃过了，但是一直无法强刷缓存，只能费劲巴拉重置系统才能强制清缓存。

反正Kindle系统辣鸡就是了！

感谢大佬秒回！

**Comment by weijarz** [comment]
是很奇怪，从来没人反馈过有这个问题，即使浏览器崩溃也不会以后再也打不开了，可能真是小概率条件被你碰上了。
