### ISSUE TITLE
近期在国内似乎无法访问服务

### ISSUE THREAD

**Issue by checcoli** [oxyry/reabble#39]
经测试，需要使用全局代理才可以访问网站

**Comment by weijarz** [comment]
用的什么网址？  reabble.com 已经被墙， reabble.cn 还没有。

**Comment by checcoli** [comment]
用的是reabble.cn，不使用代理时无法ping通
PING reabble.cn (185.218.5.103): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

**Comment by weijarz** [comment]
@checcoli 很奇怪。我这里没有问题。
且我用多地点ping网站 17ce.com 国内各省都没发现不通的。
你是什么宽带？

**Comment by weijarz** [comment]
@checcoli  换过了线路，现在可以打开了吗

**Comment by checcoli** [comment]
可以了可以了，谢谢！之前用的是学校的网络，应该是教育网吧
