### ISSUE TITLE
A standalone Android app for offline reading?

### ISSUE THREAD

**Issue by Bout2GitIt** [oxyry/reabble#51]
I love Reabble. BUT... I wish that it worked offline. Currently, it only downloads a few articles for offline reading. I would love to read my entire library offline.

I believe that offline reading is only possible if Reabble becomes a standalone Android app.  I know that there's currently [a shell Android app](https://github.com/zmk-ink/reabble-android), but it does not have offline reading. 

Can Reabble ever become a standalone Android app that supports offline reading?

Thank you.

**Comment by weijarz** [comment]
There are no plans to add offline reading to reabble.
Another of our apps qireader.com may add offline support later.
