### ISSUE TITLE
Font size too big for English in list view in Kindle Voyage Browser

### ISSUE THREAD

**Issue by lypanov** [oxyry/reabble#8]
Alas with the new updated reabble.com I'm unable to quickly clear my list as I no longer see enough of the title text in the list and have to open each article individually. Would it be possible to either a) have a font size option for the list view, b) have two rows of text? Not sure if either is possible with the CSS you're using alas.

Thank you so much! Reabble/Kindle4RSS have saved me so much time these years!

**Comment by weijarz** [comment]
Fixed.
Added a new list option  'Compact Layout'.

**Comment by lypanov** [comment]
Thank you so much!! Can get through them even faster now with this + the new redesign. The new position of the "mark all read" especially is very helpful.
