### ISSUE TITLE
新版本触控太卡顿了! 外加体验分享

### ISSUE THREAD

**Issue by luistrong** [oxyry/reabble#9]
KPW4, 一方面触控卡顿, 超过十秒没反应;
另一更重要的方面就是, 对于用惯了老版的用户来说, 新版无疑是一种巨大的倒退:
1) RSS订阅源默认隐藏, 需要二次点击才能出现, kindle本来反应就慢, 二次点击真致命;
2) kindle浏览器上面的状态栏本身不可隐藏, 新版居然又在下方加了更大更厚的导航栏, 双额头占了大面积的显示区域...醉了
3) 导航栏上面的功能键对于老版上手几分钟就能熟悉的功能, 没必要单独开一栏;
4) 竖向的进度条与操作逻辑不符, 又不是上滑翻页. 本来是点击翻页, 横向进度条, 更符合逻辑
5) 紧凑型界面也不紧凑, 只能显示6条..

以上是本人对新版体验几分钟后的感慨, 权当吐槽一下.

**Comment by weijarz** [comment]
@luistrong 
Kindle的浏览器有一个Bug，偶尔会忽略掉连续的二次点击，不是界面卡住了。
双额头只在列表上有，不是大问题。
进度条不在Kindle上用时是可以上下滑动翻页的，和普通网页一样。
二列导航栏应该会加回来（在其它浏览器上是有二列布局的，Kindle上因为发现些问题临时禁用了）。

**Comment by luistrong** [comment]
@weijarz 
感谢回复,
我这里kindle双额头在阅读文章的时候也有, 找了下不能隐藏

**Comment by weijarz** [comment]
@luistrong 你说的网页本身的顶部工具栏吧，那是有的，我是指阅读界面底下的那个没了。
